/pack2/pp_controller:
  ros__parameters:
    channel_config:
      ch0:
        micro:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        atm:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        macro:
          A_max: 0.2845
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
          I_MAX: 0.3
        chamber_volume_ml: 132.0
      ch1:
        micro:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        atm:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        macro:
          A_max: 0.2845
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
          I_MAX: 0.3
        chamber_volume_ml: 132.0
      ch2:
        micro:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        atm:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        macro:
          A_max: 0.2845
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
          I_MAX: 0.3
        chamber_volume_ml: 132.0
      ch3:
        micro:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        atm:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        macro:
          A_max: 0.2845
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
          I_MAX: 0.3
        chamber_volume_ml: 132.0
      ch4:
        micro:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        atm:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        macro:
          A_max: 0.2845
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
          I_MAX: 0.3
        chamber_volume_ml: 132.0
      ch5:
        micro:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        atm:
          A_max: 0.0442371
          k_shape: 28.35244514
          C_k: 0.05447818
          C_p: 0.0002863
          C_z: 0.00148779
          A_bw: 12061.89636753
          beta_bw: 86.06557408
          gamma_bw: 0.05306071
          alpha_shape: 15279.0018484
          wn_up: 45.25082975
          zeta_up: 0.22855531
          wn_down: 39.54669111
          zeta_down: 0.2
          I_MAX: 0.3
        macro:
          A_max: 0.2845
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
          I_MAX: 0.3
        chamber_volume_ml: 132.0
      ch6:
        micro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        atm:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        macro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        chamber_volume_ml: 132.0
      ch7:
        micro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        atm:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        macro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        chamber_volume_ml: 132.0
      ch8:
        micro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        atm:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        macro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        chamber_volume_ml: 132.0
      ch9:
        micro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        atm:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        macro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        chamber_volume_ml: 132.0
      ch10:
        micro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        atm:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        macro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        chamber_volume_ml: 132.0
      ch11:
        micro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        atm:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        macro:
          I_MAX: 0.3
          A_max: 1.778125
          k_shape: 33.09
          C_k: 0.0288
          C_p: 0.00012
          C_z: 0.0
          A_bw: 260649.5
          beta_bw: 179.0
          gamma_bw: 0.06
          alpha_shape: 3884.2
          wn_up: 40.0
          zeta_up: 1.2
          wn_down: 45.0
          zeta_down: 1.0
        chamber_volume_ml: 132.0
