#!/usr/bin/env python3
"""
Standalone pneumatic control simulation (no ROS2 required).
Paper: "Modeling and RL-Based Control of Simultaneous Positive and Negative
        Pressure Generation in Pneumatic Systems"

Physics:  mirrors PneumaticSim.cpp (valve flow + ideal gas)
Control:  mirrors compute_input_reference() in Controller.cpp (feedforward + integral)
Channels: ch0 (positive, gid=0, board 5) + ch6 (negative, gid=6, board 11)
"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import csv, os

# ── Physical constants (same as Controller.cpp) ──────────────────────────────
RGAS    = 287.0       # J/(kg·K)
TEMP_K  = 293.15      # K
LPM2KG  = 0.0002155   # kg/s per LPM  (empirical, fitted to hardware)
ATM_KPA = 101.325     # kPa

# ── Supply lines ─────────────────────────────────────────────────────────────
P_LINE_POS   = 400.0  # kPa  positive supply
P_LINE_NEG   =  50.0  # kPa  suction line
P_LINE_MACRO = 400.0  # kPa  macro supply
P_MACRO_NEG  =  50.0  # kPa  negative macro outlet

# ── Integration ──────────────────────────────────────────────────────────────
DT        = 0.002     # 500 Hz control loop
N_SUB     = 10        # Euler sub-steps per tick (0.2 ms)
T_TOTAL   = 55.0      # seconds (extended for low-frequency sine evaluation)

# ─────────────────────────────────────────────────────────────────────────────
# BiPAM Force Model
# Source: "Cooperative antagonistic mechanism driven by bidirectional pneumatic
#          artificial muscles for soft robotic joints"
#          Park, J.H., Kim, K., Gong, Y.J., et al.
#          Mechatronics 97, 2023. DOI: 10.1016/j.mechatronics.2023.103099
#
# Derivation: virtual work principle  →  F = P_gauge × (dV / dL)
#
#   Positive pressure (P > P_atm):  bellows contracts axially.
#     V(L) = π r_m² L   →   dV/dL = π r_m²
#     F_pos = (P − P_atm) × 1e3 × π r_m²                       [N]
#
#   Negative pressure (P < P_atm):  inner deformable structure extends.
#     V(L) = π r_i² L   →   dV/dL = π r_i²
#     F_neg = (P_atm − P) × 1e3 × π r_i²                       [N]
#
#   Length-dependent correction (geometric nonlinearity):
#     F(ε) = F₀ × (1 + c₁ε + c₂ε²)
#     ε_pos = (L₀ − L) / L₀  ∈ [0, 0.751]   (contraction strain, paper max 75.1 %)
#     ε_neg = (L − L₀)  / L₀ ∈ [0, 4.021]   (extension  strain, paper max 402.1 %)
#
# Effective radii are back-calculated from the paper's peak force data:
#   F_pos_max = 124.46 N  @ ΔP_pos = P_LINE_POS − ATM = 298.7 kPa
#     → r_m   = sqrt(124.46 / (298675 × π)) ≈ 11.5 mm
#   F_neg_max = 122.80 N  @ ΔP_neg = ATM − P_LINE_NEG =  51.3 kPa
#     → r_i   = sqrt(122.80 / ( 51325 × π)) ≈ 27.6 mm
#
# Calibrate _BIPAM geometry and polynomial coefficients from the paper's
# measured force–stroke curves before use in real hardware.
# ─────────────────────────────────────────────────────────────────────────────

_BIPAM = dict(
    L0          = 0.15,       # m   max extension length per chamber (50 mm dia spec)
    r_m         = 0.025,      # m   effective radius = 50 mm / 2   (positive pressure)
    r_i         = 0.025,      # m   effective radius = 50 mm / 2   (negative pressure)
    # Polynomial correction: F(ε)/F₀ = 1 + c₁ε + c₂ε²
    # Positive: force decreases as bellows approaches full contraction
    c_pos       = (-0.80, 0.30),
    # Negative: force grows slightly then flattens as inner tube fully extends
    c_neg       = ( 0.50, -0.10),
    eps_max_pos = 0.751,      # clamp contraction strain to paper limit
    eps_max_neg = 4.021,      # clamp extension  strain to paper limit
)


def bipam_force_pos(P_kPa, L_m=None):
    """
    BiPAM contraction force [N] generated by positive (above-atm) pressure.

    P_kPa : absolute chamber pressure [kPa]
    L_m   : current actuator length [m]; None → skip length correction

    Returns force in the contraction direction (≥ 0).
    """
    dP = max(0.0, P_kPa - ATM_KPA) * 1e3       # Pa gauge
    F0 = dP * np.pi * _BIPAM['r_m'] ** 2        # [N]
    if L_m is None or F0 == 0.0:
        return F0
    eps = np.clip((_BIPAM['L0'] - L_m) / _BIPAM['L0'], 0.0, _BIPAM['eps_max_pos'])
    c1, c2 = _BIPAM['c_pos']
    return max(0.0, F0 * (1.0 + c1 * eps + c2 * eps ** 2))


def bipam_force_neg(P_kPa, L_m=None):
    """
    BiPAM extension force [N] generated by negative (below-atm) pressure.

    P_kPa : absolute chamber pressure [kPa]
    L_m   : current actuator length [m]; None → skip length correction

    Returns force in the extension direction (≥ 0).
    """
    dP = max(0.0, ATM_KPA - P_kPa) * 1e3        # Pa gauge (magnitude)
    F0 = dP * np.pi * _BIPAM['r_i'] ** 2         # [N]
    if L_m is None or F0 == 0.0:
        return F0
    eps = np.clip((L_m - _BIPAM['L0']) / _BIPAM['L0'], 0.0, _BIPAM['eps_max_neg'])
    c1, c2 = _BIPAM['c_neg']
    return max(0.0, F0 * (1.0 + c1 * eps + c2 * eps ** 2))


def bipam_net_force(P_pos_kPa, P_neg_kPa, L_m=None):
    """
    Series cooperative net force [N].

    Positive BiPAM (ch0) and negative BiPAM (ch6) are connected in series
    and act in the same direction.  Positive return = output direction.

    P_pos_kPa : ch0 absolute pressure [kPa]
    P_neg_kPa : ch6 absolute pressure [kPa]
    L_m       : actuator length [m] (shared geometric axis)
    """
    return bipam_force_pos(P_pos_kPa, L_m) + bipam_force_neg(P_neg_kPa, L_m)


# ─────────────────────────────────────────────────────────────────────────────
# Physics
# ─────────────────────────────────────────────────────────────────────────────

def calc_flow(u_pct, P_in, P_out, k0, k1, k2):
    """Valve flow [LPM].  flow = (k0*Pin + k1*u - k2)*sqrt(2*(Pin-Pout)*Pin)"""
    u_pct = max(0.0, min(100.0, u_pct))
    if P_in <= P_out:
        return 0.0
    root = (2.0 * (P_in - P_out) * P_in) ** 0.5
    return max(0.0, min(100.0, (k0 * P_in + k1 * u_pct - k2) * root))

def dPdt(P_now, u_mi, u_at, u_ma, k0, k1, k2, V, is_pos):
    """Returns dP/dt [kPa/s]."""
    if is_pos:
        net = ( calc_flow(u_mi, P_LINE_POS,   P_now, k0, k1, k2)
              + calc_flow(u_ma, P_LINE_MACRO,  P_now, k0, k1, k2)
              - calc_flow(u_at, P_now,         ATM_KPA, k0, k1, k2) )
    else:
        net = ( calc_flow(u_at, ATM_KPA,       P_now, k0, k1, k2)
              - calc_flow(u_mi, P_now,         P_LINE_NEG,  k0, k1, k2)
              - calc_flow(u_ma, P_now,         P_MACRO_NEG, k0, k1, k2) )
    return (RGAS * TEMP_K / V) * LPM2KG * net / 1000.0

# ─────────────────────────────────────────────────────────────────────────────
# Controller  (mirrors compute_input_reference in Controller.cpp)
# ─────────────────────────────────────────────────────────────────────────────

def compute_uref(P_now, P_ref, k0, k1, k2, V, is_pos,
                 TC, ki_mi, ki_ma, ki_at, macro_thr, integral, dt):
    """
    Feedforward + integral.
    Returns (u_mi, u_ma, u_at, new_integral).
    Mirrors compute_input_reference() including sign-flip & anti-windup reset.
    """
    err = P_ref - P_now
    # Integral update with anti-windup reset (mirrors Controller.cpp line 319-331)
    # Positive: intg += err*dt,  reset when sign(err) != sign(intg)
    # Negative: intg -= err*dt,  reset when sign(err) == sign(intg)
    if is_pos:
        if (err > 0 and integral < 0) or (err < 0 and integral > 0):
            integral = 0.0
        intg = max(-1000.0, min(1000.0, integral + err * dt))
    else:
        if (err > 0 and integral > 0) or (err < 0 and integral < 0):
            integral = 0.0
        intg = max(-1000.0, min(1000.0, integral - err * dt))

    # desired mass flow [LPM]
    P_dot = err * 1000.0 / max(1e-3, TC)          # Pa/s
    m_dot = P_dot * V / (RGAS * TEMP_K) / LPM2KG  # LPM

    u_mi = u_ma = u_at = 0.0

    def inv_valve(flow_req, P_in, P_out):
        """Invert calc_flow to get required u."""
        denom = (2.0 * P_in * max(1e-3, P_in - P_out)) ** 0.5
        return (abs(flow_req) / max(1e-9, denom) + k2 - k0 * P_in) / max(1e-9, k1)

    if is_pos:
        if m_dot > 0:                            # fill
            u_mi = inv_valve(m_dot, P_LINE_POS,  P_now) + ki_mi * intg
            if abs(err) >= macro_thr:
                u_ma = inv_valve(m_dot, P_LINE_MACRO, P_now) + ki_ma * intg
        else:                                    # exhaust
            u_at = inv_valve(m_dot, P_now, ATM_KPA) + ki_at * abs(intg)
    else:
        if m_dot < 0:                            # exhaust (decrease P toward suction)
            u_mi = inv_valve(m_dot, P_now, P_LINE_NEG) + ki_mi * intg
            if abs(err) >= macro_thr:
                u_ma = inv_valve(m_dot, P_now, P_MACRO_NEG) + ki_ma * intg
        else:                                    # fill (increase P toward atm)
            u_at = inv_valve(m_dot, ATM_KPA, P_now) + ki_at * abs(intg)

    clip = lambda x: max(0.0, min(100.0, x))
    return clip(u_mi), clip(u_ma), clip(u_at), intg

# ─────────────────────────────────────────────────────────────────────────────
# Reference trajectory
# ─────────────────────────────────────────────────────────────────────────────

def reference(t):
    """
    ch0 (positive): 0-2s hold atm, 2-6s step 150, 6-10s step 200,
                    10-14s step 130, 14-20s sine 165+35*sin(2π(t-14)/4)
    ch6 (negative): 0-2s hold atm, 2-6s step 85, 6-10s step 72,
                    10-14s step 90,  14-20s sine 80+8*sin(2π(t-14)/4)
    """
    # Sine starts smoothly from the previous step level (no discontinuity at t=14)
    if t < 2.0:
        rp, rn = ATM_KPA, ATM_KPA
    elif t < 6.0:
        rp, rn = 150.0, 85.0
    elif t < 10.0:
        rp, rn = 200.0, 72.0
    elif t < 14.0:
        rp, rn = 130.0, 90.0
    else:
        # Center chosen so sine(0)=0 means ref starts at 130 / 90 (no jump)
        phase = 2.0 * np.pi * (t - 14.0) / 20.0   # 0.05 Hz  (was 0.25 Hz)
        rp = 130.0 + 35.0 * np.sin(phase)           # 95 ~ 165 kPa
        rn =  90.0 -  8.0 * np.sin(phase)           # 82 ~ 98 kPa
    return rp, rn

# ─────────────────────────────────────────────────────────────────────────────
# Simulation runner
# ─────────────────────────────────────────────────────────────────────────────

def run(params_pos, params_neg):
    """
    params: dict with keys k0,k1,k2,volume_m3,TC,ki_mi,ki_ma,ki_at,macro_thr
    Returns arrays dict.
    """
    N  = int(T_TOTAL / DT)
    dt_sub = DT / N_SUB

    def unpack(p):
        return (p['k0'], p['k1'], p['k2'], p['volume_m3'],
                p['TC'], p['ki_mi'], p['ki_ma'], p['ki_at'], p['macro_thr'])

    k0p,k1p,k2p,Vp,TCp,kmi_p,kma_p,kat_p,mt_p = unpack(params_pos)
    k0n,k1n,k2n,Vn,TCn,kmi_n,kma_n,kat_n,mt_n = unpack(params_neg)

    P_pos = ATM_KPA; P_neg = ATM_KPA
    int_pos = int_neg = 0.0

    t_arr = np.empty(N); rp_arr = np.empty(N); rn_arr = np.empty(N)
    P_pos_arr = np.empty(N); P_neg_arr = np.empty(N)
    umi_p = np.empty(N); uma_p = np.empty(N); uat_p = np.empty(N)
    umi_n = np.empty(N); uma_n = np.empty(N); uat_n = np.empty(N)
    F_pos_arr = np.empty(N); F_neg_arr = np.empty(N); F_net_arr = np.empty(N)

    for k in range(N):
        t = k * DT
        rp, rn = reference(t)

        u_mi_p, u_ma_p, u_at_p, int_pos = compute_uref(
            P_pos, rp, k0p,k1p,k2p,Vp, True,
            TCp, kmi_p, kma_p, kat_p, mt_p, int_pos, DT)
        u_mi_n, u_ma_n, u_at_n, int_neg = compute_uref(
            P_neg, rn, k0n,k1n,k2n,Vn, False,
            TCn, kmi_n, kma_n, kat_n, mt_n, int_neg, DT)

        for _ in range(N_SUB):
            dp = dPdt(P_pos, u_mi_p, u_at_p, u_ma_p, k0p,k1p,k2p,Vp, True)
            dn = dPdt(P_neg, u_mi_n, u_at_n, u_ma_n, k0n,k1n,k2n,Vn, False)
            P_pos = max(50.0,  min(800.0, P_pos + dp * dt_sub))
            P_neg = max(10.0,  min(110.0, P_neg + dn * dt_sub))

        t_arr[k]=t; rp_arr[k]=rp; rn_arr[k]=rn
        P_pos_arr[k]=P_pos; P_neg_arr[k]=P_neg
        umi_p[k]=u_mi_p; uma_p[k]=u_ma_p; uat_p[k]=u_at_p
        umi_n[k]=u_mi_n; uma_n[k]=u_ma_n; uat_n[k]=u_at_n
        F_pos_arr[k] = bipam_force_pos(P_pos)
        F_neg_arr[k] = bipam_force_neg(P_neg)
        F_net_arr[k] = bipam_net_force(P_pos, P_neg)

    return dict(t=t_arr, rp=rp_arr, rn=rn_arr,
                P_pos=P_pos_arr, P_neg=P_neg_arr,
                umi_p=umi_p, uma_p=uma_p, uat_p=uat_p,
                umi_n=umi_n, uma_n=uma_n, uat_n=uat_n,
                F_pos=F_pos_arr, F_neg=F_neg_arr, F_net=F_net_arr)

# ─────────────────────────────────────────────────────────────────────────────
# Output helpers
# ─────────────────────────────────────────────────────────────────────────────

def rmse(a, b, t, t_start=2.0):
    mask = t >= t_start
    return float(np.sqrt(np.mean((a[mask]-b[mask])**2)))

def save_csv(d, path):
    with open(path, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['t_s','ref_pos_kPa','P_pos_kPa','ref_neg_kPa','P_neg_kPa',
                    'u_mi_pos','u_ma_pos','u_at_pos',
                    'u_mi_neg','u_ma_neg','u_at_neg',
                    'F_pos_N','F_neg_N','F_net_N'])
        for i in range(len(d['t'])):
            w.writerow([f"{d['t'][i]:.4f}",
                        f"{d['rp'][i]:.4f}", f"{d['P_pos'][i]:.4f}",
                        f"{d['rn'][i]:.4f}", f"{d['P_neg'][i]:.4f}",
                        f"{d['umi_p'][i]:.2f}",f"{d['uma_p'][i]:.2f}",f"{d['uat_p'][i]:.2f}",
                        f"{d['umi_n'][i]:.2f}",f"{d['uma_n'][i]:.2f}",f"{d['uat_n'][i]:.2f}",
                        f"{d['F_pos'][i]:.3f}",f"{d['F_neg'][i]:.3f}",f"{d['F_net'][i]:.3f}"])

def plot(d, title, path):
    fig, axes = plt.subplots(3, 2, figsize=(14, 13))
    fig.suptitle(title, fontsize=13, fontweight='bold')
    t = d['t']

    # ── Positive pressure ────────────────────────────────────────
    ax = axes[0,0]
    ax.plot(t, d['rp'],    'k--', lw=1.5, label='ref')
    ax.plot(t, d['P_pos'], 'b-',  lw=1.5, label='actual')
    ax.axvline(2,  color='gray', lw=0.7, ls=':')
    ax.axvline(6,  color='gray', lw=0.7, ls=':')
    ax.axvline(10, color='gray', lw=0.7, ls=':')
    ax.axvline(14, color='gray', lw=0.7, ls=':')
    ax.set_ylabel('Pressure [kPa]'); ax.set_title('ch0  Positive Channel')
    ax.legend(loc='upper left'); ax.grid(True, alpha=0.3)
    ax.set_xlim(0, T_TOTAL)
    e_p = rmse(d['P_pos'], d['rp'], t)
    ax.text(0.98, 0.05, f'RMSE={e_p:.2f} kPa',
            transform=ax.transAxes, ha='right', fontsize=9,
            bbox=dict(boxstyle='round', fc='white', alpha=0.7))

    # ── Negative pressure ────────────────────────────────────────
    ax = axes[0,1]
    ax.plot(t, d['rn'],    'k--', lw=1.5, label='ref')
    ax.plot(t, d['P_neg'], 'r-',  lw=1.5, label='actual')
    for xv in [2,6,10,14]: ax.axvline(xv, color='gray', lw=0.7, ls=':')
    ax.set_ylabel('Pressure [kPa]'); ax.set_title('ch6  Negative Channel')
    ax.legend(loc='upper left'); ax.grid(True, alpha=0.3)
    ax.set_xlim(0, T_TOTAL)
    e_n = rmse(d['P_neg'], d['rn'], t)
    ax.text(0.98, 0.05, f'RMSE={e_n:.2f} kPa',
            transform=ax.transAxes, ha='right', fontsize=9,
            bbox=dict(boxstyle='round', fc='white', alpha=0.7))

    # ── Positive inputs ──────────────────────────────────────────
    ax = axes[1,0]
    ax.plot(t, d['umi_p'], 'b-',  lw=1.0, label='u_micro')
    ax.plot(t, d['uat_p'], 'g-',  lw=1.0, label='u_atm')
    ax.plot(t, d['uma_p'], 'm-',  lw=1.0, label='u_macro')
    ax.set_ylabel('Valve opening [%]'); ax.set_title('ch0  Control Inputs')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3); ax.set_xlim(0, T_TOTAL); ax.set_ylim(-5, 105)

    # ── Negative inputs ──────────────────────────────────────────
    ax = axes[1,1]
    ax.plot(t, d['umi_n'], 'b-',  lw=1.0, label='u_micro')
    ax.plot(t, d['uat_n'], 'g-',  lw=1.0, label='u_atm')
    ax.plot(t, d['uma_n'], 'm-',  lw=1.0, label='u_macro')
    ax.set_ylabel('Valve opening [%]'); ax.set_title('ch6  Control Inputs')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3); ax.set_xlim(0, T_TOTAL); ax.set_ylim(-5, 105)

    # ── Force: individual channels ───────────────────────────────
    ax = axes[2,0]
    ax.plot(t, d['F_pos'], 'b-', lw=1.5, label='F_pos (contraction)')
    ax.plot(t, d['F_neg'], 'r-', lw=1.5, label='F_neg (extension)')
    for xv in [2,6,10,14]: ax.axvline(xv, color='gray', lw=0.7, ls=':')
    ax.set_ylabel('Force [N]'); ax.set_title('BiPAM Channel Forces')
    ax.set_xlabel('Time [s]'); ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3); ax.set_xlim(0, T_TOTAL)

    # ── Force: net cooperative-antagonistic ──────────────────────
    ax = axes[2,1]
    ax.plot(t, d['F_net'], 'k-', lw=1.5, label='F_net')
    ax.axhline(0, color='gray', lw=0.8, ls='--')
    for xv in [2,6,10,14]: ax.axvline(xv, color='gray', lw=0.7, ls=':')
    ax.set_ylabel('Net Force [N]'); ax.set_title('BiPAM Net Force (series cooperative: pos + neg)')
    ax.set_xlabel('Time [s]'); ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3); ax.set_xlim(0, T_TOTAL)

    plt.tight_layout()
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()

def plot_comparison(results, path):
    """Overlay multiple gain sets on one figure."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    colors = [f'C{i}' for i in range(len(results))]
    t = results[0][1]['t']

    for ax, key, ref_key, ylabel, title in [
        (axes[0], 'P_pos', 'rp', 'Pressure [kPa]', 'ch0 Positive – gain comparison'),
        (axes[1], 'P_neg', 'rn', 'Pressure [kPa]', 'ch6 Negative – gain comparison'),
    ]:
        ax.plot(t, results[0][1][ref_key], 'k--', lw=1.5, label='ref', zorder=5)
        for i, (label, d) in enumerate(results):
            e = rmse(d[key], d[ref_key], t)
            ax.plot(t, d[key], color=colors[i], lw=1.2,
                    label=f'{label}  RMSE={e:.2f}')
        for xv in [2,6,10,14]: ax.axvline(xv, color='gray', lw=0.6, ls=':')
        ax.set_xlabel('Time [s]'); ax.set_ylabel(ylabel); ax.set_title(title)
        ax.legend(fontsize=8); ax.grid(True, alpha=0.3); ax.set_xlim(0, T_TOTAL)

    plt.tight_layout()
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()

# ─────────────────────────────────────────────────────────────────────────────
# Gain sets to compare
# ─────────────────────────────────────────────────────────────────────────────

BASE_POS = dict(k0=0.00022, k1=0.010, k2=0.75, volume_m3=1e-6)
BASE_NEG = dict(k0=0.00022, k1=0.008, k2=0.70, volume_m3=1e-6)

GAINS = [
    # label,  TC_pos, ki_mi_pos, ki_ma_pos, ki_at_pos, macro_pos,
    #         TC_neg, ki_mi_neg, ki_ma_neg, ki_at_neg, macro_neg
    ("slow",    2.0, 0.00, 0.00, 0.00, 30.0,   2.0, 0.00, 0.00, 0.00, 20.0),
    ("medium",  1.0, 0.05, 0.02, 0.05, 25.0,   1.0, 0.10, 0.05, 0.20, 15.0),
    ("tuned",   0.5, 0.15, 0.08, 0.15, 20.0,   0.5, 0.30, 0.15, 0.50, 12.0),
    ("fast",    0.3, 0.25, 0.12, 0.25, 15.0,   0.3, 0.50, 0.25, 0.80, 10.0),
    ("fast2",   0.25,0.30, 0.15, 0.30, 12.0,   0.25,0.70, 0.35, 1.00,  8.0),
    ("fast3",   0.20,0.35, 0.18, 0.35, 10.0,   0.20,0.90, 0.45, 1.20,  7.0),
]

def make_params(row):
    lbl, TC_p, kmi_p, kma_p, kat_p, mt_p, TC_n, kmi_n, kma_n, kat_n, mt_n = row
    pos = {**BASE_POS, 'TC':TC_p,'ki_mi':kmi_p,'ki_ma':kma_p,'ki_at':kat_p,'macro_thr':mt_p}
    neg = {**BASE_NEG, 'TC':TC_n,'ki_mi':kmi_n,'ki_ma':kma_n,'ki_at':kat_n,'macro_thr':mt_n}
    return lbl, pos, neg

# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    out = 'results'
    os.makedirs(out, exist_ok=True)

    results = []
    best_label, best_data, best_rmse = None, None, 1e9

    print(f"{'Label':<10} {'RMSE_pos':>10} {'RMSE_neg':>10}  {'total':>10}")
    print('-' * 46)

    for row in GAINS:
        lbl, pp, pn = make_params(row)
        d = run(pp, pn)
        results.append((lbl, d))

        ep = rmse(d['P_pos'], d['rp'], d['t'])
        en = rmse(d['P_neg'], d['rn'], d['t'])
        total = ep + en
        print(f"{lbl:<10} {ep:>10.3f} {en:>10.3f}  {total:>10.3f}")

        if total < best_rmse:
            best_rmse, best_label, best_data = total, lbl, d

    print(f"\nBest: {best_label}")

    # Save best result
    save_csv(best_data, f'{out}/sim_result_best.csv')
    plot(best_data,
         f'Pneumatic Sim  [{best_label}]  ch0(+) + ch6(-)  –  20 s',
         f'{out}/sim_result_best.png')

    # Save comparison
    plot_comparison(results, f'{out}/sim_comparison.png')

    # Also save all CSVs
    for lbl, d in results:
        save_csv(d, f'{out}/sim_{lbl}.csv')

    print(f"\nOutput files:")
    for f in sorted(os.listdir(out)):
        size = os.path.getsize(f'{out}/{f}')
        print(f"  {out}/{f}  ({size/1024:.1f} KB)")

    # Diagnostics on best result
    d  = best_data
    t  = np.array(d['t'])
    Pp = np.array(d['P_pos']); rp = np.array(d['rp'])
    Pn = np.array(d['P_neg']); rn = np.array(d['rn'])

    def settling(t, P, t_step, r_target, tol=2.0):
        idx = np.where(t > t_step)[0]
        for i in idx:
            if all(abs(P[i:i+50] - r_target) < tol):
                return t[i] - t_step
        return float('nan')

    print(f"\nSettling time (±2 kPa, from step edge):")
    sp1 = settling(t, Pp, 2.0, 150.0)
    sn1 = settling(t, Pn, 2.0,  85.0)
    sp2 = settling(t, Pp, 6.0, 200.0)
    sn2 = settling(t, Pn, 6.0,  72.0)
    sp3 = settling(t, Pp,10.0, 130.0)
    sn3 = settling(t, Pn,10.0,  90.0)
    print(f"  Positive  101→150 kPa (t=2s): {sp1:.3f} s")
    print(f"  Negative  101→85  kPa (t=2s): {sn1:.3f} s")
    print(f"  Positive  150→200 kPa (t=6s): {sp2:.3f} s")
    print(f"  Negative   85→72  kPa (t=6s): {sn2:.3f} s")
    print(f"  Positive  200→130 kPa (t=10s): {sp3:.3f} s")
    print(f"  Negative   72→90  kPa (t=10s): {sn3:.3f} s")

    mask_sine = t >= 14.0
    ep_sine = abs(Pp[mask_sine] - rp[mask_sine])
    en_sine = abs(Pn[mask_sine] - rn[mask_sine])
    rmse_ep = np.sqrt(np.mean(ep_sine**2))
    rmse_en = np.sqrt(np.mean(en_sine**2))
    print(f"\nSine tracking (t=14-20s):")
    print(f"  Positive: RMSE={rmse_ep:.3f} kPa  peak_err={ep_sine.max():.3f} kPa")
    print(f"  Negative: RMSE={rmse_en:.3f} kPa  peak_err={en_sine.max():.3f} kPa")
